// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACpUMCIqBzIZaEGlxGNr_RDlzUp9vm6ro',
    appId: '1:327970491953:web:01377d5a1b173746c04f10',
    messagingSenderId: '327970491953',
    projectId: 'ok-ko-9890d',
    authDomain: 'ok-ko-9890d.firebaseapp.com',
    storageBucket: 'ok-ko-9890d.appspot.com',
    measurementId: 'G-R8CYC8KMRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGFNwsGRhhwxcNuliiIsf9buq2k1Dnylo',
    appId: '1:327970491953:android:7d0ab2b147cda723c04f10',
    messagingSenderId: '327970491953',
    projectId: 'ok-ko-9890d',
    storageBucket: 'ok-ko-9890d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXXa4M_q5iOKgYI6gqlh_uUkRFJ-PT2OM',
    appId: '1:327970491953:ios:41b8d90205f78ffac04f10',
    messagingSenderId: '327970491953',
    projectId: 'ok-ko-9890d',
    storageBucket: 'ok-ko-9890d.appspot.com',
    iosBundleId: 'com.example.koOk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXXa4M_q5iOKgYI6gqlh_uUkRFJ-PT2OM',
    appId: '1:327970491953:ios:75b2784495e684e9c04f10',
    messagingSenderId: '327970491953',
    projectId: 'ok-ko-9890d',
    storageBucket: 'ok-ko-9890d.appspot.com',
    iosBundleId: 'com.example.koOk.RunnerTests',
  );
}
